<html>
<head>
    <meta charset="utf-8"/>
    <style>
        @page { margin: 28px 32px; }

        body {
            font-family: DejaVu Sans, Arial, Helvetica, sans-serif;
            font-size: 11px;
            color: #1f2430;
        }

        .masthead {
            border-bottom: 2px solid #5145cd;
            padding-bottom: 10px;
            margin-bottom: 18px;
        }

        .masthead h1 { margin: 0; font-size: 20px; letter-spacing: -0.2px; }
        .masthead .meta { margin-top: 4px; font-size: 10px; color: #6b7280; }

        .totals { width: 100%; border-collapse: separate; border-spacing: 6px 0; margin-bottom: 20px; }

        .totals td {
            background: #f6f7f9;
            border: 1px solid #e6e8ec;
            border-radius: 4px;
            padding: 10px 12px;
            width: 25%;
        }

        .totals .label { font-size: 9px; text-transform: uppercase; letter-spacing: 0.6px; color: #6b7280; }
        .totals .value { font-size: 15px; font-weight: bold; padding-top: 3px; }

        h2 { font-size: 12px; text-transform: uppercase; letter-spacing: 0.8px; color: #6b7280; margin: 0 0 8px; }

        table.rows { width: 100%; border-collapse: collapse; }

        table.rows th {
            text-align: left;
            font-size: 9px;
            text-transform: uppercase;
            letter-spacing: 0.6px;
            color: #6b7280;
            border-bottom: 1px solid #d1d5db;
            padding: 6px 8px;
        }

        table.rows td { padding: 7px 8px; border-bottom: 1px solid #eceef1; }
        table.rows tr:nth-child(even) td { background: #fafbfc; }

        .num { text-align: right; }

        .flag {
            display: inline-block;
            padding: 1px 6px;
            border-radius: 8px;
            font-size: 9px;
        }

        .flag-out { background: #fde2e4; color: #9b1c2e; }
        .flag-low { background: #fff3cd; color: #8a5a00; }
        .flag-ok  { background: #e3f5e9; color: #1c6b3c; }

        .empty { padding: 24px 8px; color: #6b7280; font-style: italic; }
        .foot { margin-top: 18px; font-size: 9px; color: #9ca3af; }
    </style>
</head>
<body>

<div class="masthead">
    <h1>Stock on hand</h1>
    <div class="meta">
        @if(trim($shopName)) {{ trim($shopName) }} &middot; @endif
        printed {{ $printed }}
    </div>
</div>

<table class="totals">
    <tr>
        <td>
            <div class="label">Products</div>
            <div class="value">{{ $products->count() }}</div>
        </td>
        <td>
            <div class="label">Units held</div>
            <div class="value">{{ number_format($units) }}</div>
        </td>
        <td>
            <div class="label">Stock value</div>
            <div class="value">{{ number_format($value, 2) }}</div>
        </td>
        <td>
            <div class="label">Low / out</div>
            <div class="value">{{ $lowCount }} / {{ $outCount }}</div>
        </td>
    </tr>
</table>

<h2>Catalogue</h2>

<table class="rows">
    <thead>
    <tr>
        <th>Product</th>
        <th>Category</th>
        <th>Unit</th>
        <th class="num">Price</th>
        <th class="num">In stock</th>
        <th class="num">Value</th>
        <th>State</th>
    </tr>
    </thead>
    <tbody>
    @forelse ($products as $product)
        <tr>
            <td>{{ $product->name }}</td>
            <td>{{ optional($product->category)->name ?? '&mdash;' }}</td>
            <td>{{ $product->unit }}</td>
            <td class="num">{{ number_format((float) $product->price, 2) }}</td>
            <td class="num">{{ number_format($product->stock) }}</td>
            <td class="num">{{ number_format($product->stock * (float) $product->price, 2) }}</td>
            <td>
                @if($product->stock_state === 'out')
                    <span class="flag flag-out">Out of stock</span>
                @elseif($product->stock_state === 'low')
                    <span class="flag flag-low">Low &mdash; {{ $product->stock }} left</span>
                @else
                    <span class="flag flag-ok">In stock</span>
                @endif
            </td>
        </tr>
    @empty
        <tr>
            <td class="empty" colspan="7">No products in the catalogue yet.</td>
        </tr>
    @endforelse
    </tbody>
</table>

<div class="foot">Generated by the POS application.</div>

</body>
</html>
